Use a constructor to initialize SFilesSet
Using a constructor to initialize the struct members, instead of
an empty initializer list (where the other members are implicitly
initialized to zero) probably is more idiomatic C++.

This fixes compilation with STLPort with GCC 4.9 from Android NDK r10
(broken since d66bc655933be3).

The fact that this only is an issue there could indicate that it
actually was a compiler bug though, but the workaround shouldn't
hurt in this case either. The issue seems to come from the array of
string in the struct, with compiler errors like these:

welsenc.cpp:766:19: error: converting to 'std::string {aka std::basic_string<char, std::char_traits<char>, std::allocator<char> >}' from initializer list would use explicit constructor 'std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const allocator_type&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::allocator_type = std::allocator<char>]'
   SFilesSet fs = {};
                   ^